name: "Hello World"
description: "Greet someone"
inputs:
  whom-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Say secret
      run: echo "::add-mask::Secret word"
      shell: bash

    - name: Say group
      run: |
        echo "::group::My title!"
        echo "Hello"
        echo "World"
        echo "!!!"
        echo "::endgroup::"
      shell: bash

    - name: Say MD
      run: |
        echo "### House M.D." >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Notice me
      run: |
        echo "::notice file=tsconfig.json,line=1,col=5,endColumn=7::Missing semicolon"
      shell: bash

    - name: Random number generator
      id: random-number-generator
      run: echo "random-number=$((1 + RANDOM % 10))" >> $GITHUB_OUTPUT
      shell: bash
    - name: Say hello
      run: echo "Hello ${{ inputs.whom-to-greet }}"
      shell: bash
