name: "Hello world"
description: "Greet someone and record the time"
inputs:
  whom-to-greet:
    description: "Whom to greete?"
    required: true
    default: "World"
outputs:
  time:
    description: "The time we greeted you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.whom-to-greet }}
