name: Matrix workflow

on:
  workflow_call:
    inputs:
      count:
        description: "How much to count?"
        required: true
        type: number

jobs:
  counter_matrix:
    continue-on-error: false
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        count: ${{ join(echo {0..inputs.count..1}, ',') }} | echo "\'\[$1\]\'" | ${{ fromJSON($1) }}
    runs-on: ubuntu-latest
    steps:
      - name: Emit
        id: emit-count
        run: echo "Count is ${{ matrix.count }}"
