name: Matrix workflow

on:
  workflow_call:
    inputs:
      count:
        description: "How much to count?"
        required: true
        type: number

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Define Colors
        id: colors
        run: |
          echo 'colors=[1, 2, 3]' >> "$GITHUB_OUTPUT"

  counter_matrix:
    needs: prepare_matrix
    continue-on-error: false
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        count: ${{ fromJSON(needs.prepare_matrix.outputs.colors) }}
    runs-on: ubuntu-latest
    steps:
      - name: Emit
        id: emit-count
        run: echo "Count is ${{ matrix.count }}"
