name: Matrix workflow

on:
  workflow_call:
    inputs:
      count:
        description: "How much to count?"
        required: true
        type: number

jobs:
  counter_matrix:
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        count: ${{ fromJSON(echo {0..inputs.count..1}) }}
    runs-on: ubuntu-latest
    steps:
      - name: Emit
        id: emit-count
        run: echo "Count is ${{ matrix.count }}"
